package com.neurix.hris.transaksi.payroll.bo.impl;

import java.math.BigDecimal;
import com.neurix.hris.transaksi.payroll.model.PayrollPendapatanPphDTO;

public class ModulePayroll
{
    protected PayrollPendapatanPphDTO generateZeroPayrollPendapatan() {
        final PayrollPendapatanPphDTO payrollPendapatanPphDTO = new PayrollPendapatanPphDTO();
        payrollPendapatanPphDTO.setPdp01(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph01(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp02(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph02(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp03(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph03(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp04(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph04(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp05(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph05(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp06(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph06(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp07(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph07(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp08(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph08(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp09(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph09(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp10(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph10(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp11(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph11(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdp12(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPph12(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdpDidik(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphDidik(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdpThr(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphThr(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdpBonus(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphBonus(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setJbtBonus(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdpRapel(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphRapel(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setRpl1(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPdpJubel(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphLain(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setJumlahGaji(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setJumlahPphGaji(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt01(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt01(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt02(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt02(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt03(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt03(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt04(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt04(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt05(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt05(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt06(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt06(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt07(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt07(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt08(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt08(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt09(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt09(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt10(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt10(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt11(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt11(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setTunObt12(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setPphObt12(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setJumlahObt(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setJumlahPphObt(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr01(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr02(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr03(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr04(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr05(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr06(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr07(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr08(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr09(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr10(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr11(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setLbr12(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setJumlahlbr(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setJumlahPphLbr(BigDecimal.ZERO);
        payrollPendapatanPphDTO.setJumlahPdpLbrObt(BigDecimal.ZERO);
        return payrollPendapatanPphDTO;
    }
}
